{% set name = "codespell" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 569b67e5e5c3ade02a1e23f6bbc56c64b608a3ab48ddd943ece0a03e6c346ed1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - codespell = codespell_lib:_script_main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - codespell --version

about:
  home: https://github.com/codespell-project/codespell
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Fix common misspellings in text files, usually source code.

  description: |
    Fix common misspellings in text files. It's designed primarily for
    checking misspelled words in source code, but it can be used with
    other files as well.
  dev_url: https://github.com/codespell-project/codespell

extra:
  recipe-maintainers:
    - dopplershift
    - larsoner
