{% set name = "codespell" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19d3fe5644fef3425777e66f225a8c82d39059dcfe9edb3349a8a2cf48383ee5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - codespell = codespell_lib:_script_main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  commands:
    - codespell --version

about:
  home: https://github.com/codespell-project/codespell
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Fix common misspellings in text files, usually source code.

  description: |
    Fix common misspellings in text files. It's designed primarily for
    checking misspelled words in source code, but it can be used with
    other files as well.
  dev_url: https://github.com/codespell-project/codespell

extra:
  recipe-maintainers:
    - dopplershift
