{% set name = "codespell" %}
{% set version = "1.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25a2ecd86b9cdc111dc40a30d0ed28c578e13a0ce158d1c383f9d47811bfcd23

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - codespell = codespell_lib:_script_main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - codespell --version

about:
  home: https://github.com/codespell-project/codespell
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Fix common misspellings in text files, usually source code.

  description: |
    Fix common misspellings in text files. It's designed primarily for
    checking misspelled words in source code, but it can be used with
    other files as well.
  dev_url: https://github.com/codespell-project/codespell

extra:
  recipe-maintainers:
    - dopplershift
