travis:
  secure:
    BINSTAR_TOKEN: WDf1aBfAtZvvLwtbf5d0Omg/pc0ekYVTdLemFmM2zv5BK4JBN0eWx5RcKoQTiBAHCT6sJ6JCdTraw091XOyLfAUOJgImrDw3M8ed0F2eLB/syLjf3lnRam/tNIQlcKRpKGsTI00bXdB73hFaGMf63ga3lm6wu9No0R9OGJSUljKms77ZZNrD3MQJFY/3AoFXH+0/AUI045u7HSuxW0bDSPoPIjXosRz2eR1yBEMSgDpTyaBSorKNdH9D2nqC0hfwMPELFvsjbQ8frqbxFAn9o8u0XEFAT9G8CyN/Zt+WTLasO6LzFKAVZgwb5SqHrhhSCym1Tn3oFBkM2lz+uYh7NfBj7kRyEWU4aJrRf+yKfHm+wodLUTIE7VXB1meXBTqB4R1B3kCKp0VMBk8gwRnXblFk755LKjy+xhKARHzZEbx5J8pkfqVR2NMShtzWBYszj8V7od+XX+OvfL0bAXtYYb0FbpJYDJCKI1Y4zHfwMn521nJ5bDKyFs0ZM4EUvkupXpVMay6HOwFuFbNFzPJ2QFdorg0GrKB3otZTdqoUy9G42+Wx2NUKUB4HRGFHzQnSCZNew/8lg52CdtpiEcGFzhSn9hdMVXzygDHQOmuhe3cRJOAiQAp0vJSbELF4nNyKrR4SsuF5I/lRrTh3TjMBqMCQGWTUGwXRABFeYY32snA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
